### ISSUE TITLE
Scaling issue ?

### ISSUE THREAD

**Issue by ams-sth** [ekaaty/vinyl-theme#5]
1920 x 1080 resolution screen at global scale 125%.
 
![Libreoffice scaling issue](https://github.com/user-attachments/assets/5ae539a7-3502-4370-8171-6db900bde843)

**Comment by christiantosta** [comment]
Hi.

Libreoffice uses GTK themes, so the problem can be related to the one selected on the systemsettings, not to Vinyl application style. Please ensure you're using "Default" or "Breeze Dark" until Vinyl had implemented a GTK theme.

If you are sure that is a problem generated by Qt/KDE application style plugin, please reopen this issue with greater details attached, like logs and evidences of the problem is related to that engine.

Additionally, you can try to set the environment variable "QT_QPA_PLATFORM=xcb" temporally to see if problem is related to wayland. In that case, Fedora is about to fix a bug on it on upcomming packages of qt6-qtwayland.

![image](https://github.com/user-attachments/assets/8cd84d7b-0738-4b1c-b0a6-5562530784f7)
